######################## default configuration ####################
baseURL: /
title: Tanzraum Herisau
theme: hugo-theme-copper
paginate: 6
summaryLength: 10
defaultContentLanguage: de
disableLanguages:
  - fr
  - en # desable language from here
outputs:
  home:
    - HTML
    - RSS
markup:
  goldmark:
    renderer:
      unsafe: true