de:
  languageName: De
  languageCode: ch-de
  contentDir: content/german
  weight: 1
  footer_content: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur
  copyright: Entwickelt von Thomas

en:
  languageName: En
  languageCode: en-en
  contentDir: content/english
  weight: 2
  footer_content: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur
  copyright: Developed by Thomas
    
  
