main:
  - name: Home
    URL: /
    weight: 1

  - name: Kurse
    URL: kurse
    weight: 2

  - name: Veranstaltungen
    URL: events
    weight: 3

  - name: Raum
    URL: raum
    weight: 4

  - name: Kontakt
    URL: kontakt
    weight: 5

footer:

  - name: Datenschutzerklärung
    URL: datenschutz
    weight: 1