main:
  - name: Home
    URL: /
    weight: 1

  - name: Kontakt
    URL: contact
    weight: 2

  - name: Seiten
    hasChildren: true
    weight: 3

  - name: Subpage
    parent: Seiten
    URL: subpage

  - name: Subpage2
    parent: Seiten
    URL: subpage2

footer:
  - name: Faq
    URL: faq
    weight: 1

  - name: Terms & Conditions
    URL: terms-conditions
    weight: 2

  - name: Privacy Policy
    URL: privacy-policy
    weight: 3