main:
  - name: Home
    URL: /
    weight: 1

  - name: Kurse
    URL: kurse
    weight: 2

  - name: Veranstaltungen
    hasChildren: true
    weight: 3

  - name: Aufführungen
    parent: Veranstaltungen
    URL: auffuehrungen

  - name: Kultur Brunch
    parent: Veranstaltungen
    URL: kultur-brunch

  - name: Raum
    URL: raum
    weight: 4

  - name: Kontakt
    URL: contact
    weight: 5

footer:

  - name: Datenschutzerklärung
    URL: datenschutz
    weight: 1